### ISSUE TITLE
Mixed Content SSL

### ISSUE THREAD

**Issue by ghost** [blue-jay/blue-jay.github.io.hugo#3]
I get this when I visit the site over ssl:
![2016-11-26-093505_1920x1080_scrot](https://cloud.githubusercontent.com/assets/9986564/20639148/c22664f6-b3bb-11e6-84ab-0ad675f0e927.png)

Just wanted to let you know. Maybe you can change the baseurl of Hugo to https instead of http.

**Comment by josephspurrier** [comment]
All done, thanks for pointing that out!

https://github.com/blue-jay/blue-jay.github.io/commit/9a8b3aaecdf3f90107478a7a1416f0019e43a638
https://github.com/blue-jay/blue-jay.github.io.hugo/commit/52e98469c032fe2bfb73ef821262bca963ac0b37
https://github.com/blue-jay/jay/commit/7ac73bcbab1905901b737aaa521c0883d8370aa4
https://github.com/blue-jay/core/commit/299934addc9585d49d71b28933ac3fd5aed878d8
https://github.com/blue-jay/blueprint/commit/12ab11fca77a2b0e6bce807fe77bd7550b74c5ab
